image: mobiledevops/flutter-sdk-image

stages:
  - test
  - build
before_script:

  - flutter doctor -v
  - flutter pub get
  - flutter clean


#MASTER
master_test:
  image: cirrusci/flutter:stable 
  stage: test
  tags:
  - gitlab-runner
  script:
    - echo "testing MASTER/RELEASE Branch  " 
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
    #- flutter test test_driver/e2e  
  only:
    - master  
  artifacts:
    paths:
      - coverage
master_build_android: 
  stage: build
  tags:
  - gitlab-runner
  script:
     - flutter build apk
  only:
    - master 
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/ 
#DEVELOP
develop_test: 
  stage: test
  tags:
  - gitlab-runner
  script:
    - echo "testing DEVELOPER Branch  " 
    - flutter test 
    #- flutter test test_driver/e2e  
  only:
    - dev  
develop_build_android: 
  stage: build
  tags:
  - gitlab-runner
  before_script:
    - echo "About to build DEVELOP " 
  script:
    - echo "building DEVELOP " 
    #- /home/mikeat/runner_wd/autoMergeRequestMaster.sh
  only:
    - dev  
    


#Code Review and Merge Request Checker
NEW_FEATURE_TEST_and_AUTO_PR: 
  image: cirrusci/flutter:stable
  stage: test
  tags:
  - gitlab-runner 
  only:
    - /^feature\/*/
  except:
    - master
    - dev
  script:
    - echo "testing for Code Review and Merge Request "
    #- flutter analyze  
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
    #- /home/mikeat/runner_wd/autoMergeRequest.sh
  
#PIPELINE_TESTER
PIPELINE_TESTER: 
  image: cirrusci/flutter:latest
  stage: test
  tags:
  - gitlab-runner 
  only:
    - /^pipeline\/*/
  except:
    - master
    - dev
  script:
    # - sdkmanager --install "system-images;android-29;default;x86"
    # - echo "no" | avdmanager --verbose create avd --force --name "generic_10" --package "system-images;android-29;default;x86" --tag "default"
    - sdkmanager --install "system-images;android-28;google_apis;x86_64"
    - echo no | avdmanager create avd -n avd28 -k "system-images;android-28;google_apis;x86_64"
      # start the emulator
    - emulator -avd avd28 -no-audio -no-window &
    - flutter emulators
    - flutter emulator --launch avd28 -v
    - flutter devices
    - echo "testing for Code Review and Merge Request "
    #- flutter analyze  
    - flutter test test_driver/e2e
