image: mobiledevops/flutter-sdk-image

stages:
  - test
  - build
  - report

.shared_script: &cleanup 
  before_script:
  - flutter doctor -v
  - flutter pub get
  - flutter clean


#MASTER
master_test:
  <<: *cleanup
  image: cirrusci/flutter:stable 
  stage: test
  tags:
  - gitlab-runner
  script:
    - echo "testing MASTER/RELEASE Branch  " 
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
    #- flutter test test_driver/e2e  
  only:
    - master  
  artifacts:
    paths:
      - coverage
master_build_android: 
  <<: *cleanup
  stage: build
  tags:
  - gitlab-runner
  script:
     - flutter build apk --release --build-number=$CI_PIPELINE_ID
  only:
    - master 
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/app/outputs/apk/release/
 
#DEVELOP
develop_test: 
  <<: *cleanup
  stage: test
  tags:
  - gitlab-runner
  script:
    - echo "testing DEVELOPER Branch  " 
    - flutter test 
    #- flutter test test_driver/e2e  
  only:
    - dev  
develop_build_android:
  <<: *cleanup 
  stage: build
  tags:
  - gitlab-runner
  before_script:
    - echo "About to build DEVELOP " 
  script:
    - echo "building DEVELOP " 
    #- /home/mikeat/runner_wd/autoMergeRequestMaster.sh
  only:
    - dev  
    


#Code Review and Merge Request Checker
NEW_FEATURE_TEST_and_AUTO_PR: 
  <<: *cleanup
  image: cirrusci/flutter:stable
  stage: test
  tags:
  - gitlab-runner 
  only:
    - /^feature\/*/
    - /^Feature\/*/
  except:
    - master
    - dev
  script:
    - echo "testing for Code Review and Merge Request "
    #- flutter analyze  
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
    #- /home/mikeat/runner_wd/autoMergeRequest.sh
  
feature_report: 
  image: mike328/gitlab-telegram-bot:latest
  stage: report
  tags:
  - gitlab-runner
  script:
    - python3 /code/telegram/sendReport.py "$TELEGRAM_API_TOKEN" "$TELEGRAM_CHAT_ID"  "$CI_COMMIT_AUTHOR" " commited to $CI_PROJECT_TITLE $CI_COMMIT_BRANCH  | $CI_COMMIT_SHA - $CI_COMMIT_MESSAGE"
  only:
    - /^feature\/*/
    - /^Feature\/*/

#PIPELINE_TESTER
PIPELINE_TESTER: 
  <<: *cleanup
  image: cirrusci/flutter:latest
  stage: test
  tags:
  - gitlab-runner 
  only:
    - /^pipeline\/*/
  except:
    - master
    - dev
  script:
    - flutter build apk --stacktrace --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - build/app/outputs/apk/release/
    expire_in: 1 day
    # # - sdkmanager --install "system-images;android-29;default;x86"
    # # - echo "no" | avdmanager --verbose create avd --force --name "generic_10" --package "system-images;android-29;default;x86" --tag "default"
    # - apt-get update
    # - apt-get install -y qemu-kvm
    # - adduser $USER kvm
    # - sdkmanager --list | grep system-images
    # - echo no | sdkmanager --install "system-images;android-S;google_apis_playstore;arm64-v8a"
    # - echo "no" | avdmanager --verbose create avd --force --name "generic_10" --package "system-images;android-S;google_apis_playstore;arm64-v8a" --tag "google_apis_playstore" 
    #      # start the emulator
    # - emulator -avd @generic_10 -no-audio -no-window &
    # - adb devices
    # - flutter emulator --launch generic_10 -v
    # - flutter emulators
    # - flutter emulator --launch generic_10 -v
    # - flutter devices
    # - echo "testing for Code Review and Merge Request "
    # #- flutter analyze  
    # - flutter test test_driver/e2e
