name: streaming_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^1.0.0
  firebase_core: ^1.0.2
  equatable: ^2.0.0
  audio_service: ^0.17.0
  just_audio: ^0.7.2
  shared_preferences: ^2.0.5
  rxdart: ^0.26.0
  percent_indicator: ^3.0.1
  http: ^0.13.1
  flutter_svg: ^0.21.0-nullsafety.0
  carousel_slider: ^3.0.0
  flutter_bloc: ^7.0.0
  shimmer: ^1.1.2
  path_provider: ^2.0.1
  flutter_hls_parser: ^2.0.0
  flutter_downloader: ^1.5.2
  test: ^1.16.0
  bloc_test: ^8.0.0
  path: ^1.8.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  firebase_messaging: ^10.0.0
  location: ^4.1.1
  mockito: ^5.0.4
  check_vpn_connection : ^0.0.1
  aes_crypt: ^0.1.1
  cached_network_image: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  flutter_spinkit: ^4.1.2
  connectivity: ^3.0.3
  animated_overflow: ^2.0.0
  flutter_signin_button: ^1.1.0
  international_phone_input: ^1.0.4
  otp_text_field: ^1.1.1
  package_info_plus: ^1.0.4
  flutter_local_notifications: ^5.0.0
  get_it: ^7.1.3
  animated_rotation: ^2.0.0
  pausable_timer: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner:
  flutter_native_splash: ^1.1.8+4
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sewasew_logo.png
  android: true
  ios : true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/json/
    - assets/audio/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
