#!/usr/bin/env python
import sys, re, os
from subprocess import check_output
commit_msg_filepath = sys.argv[1]
f=open(commit_msg_filepath, "r")
commit_msg=f.read()
issue_checker=False
feature_checker=False
if "Fixes" in commit_msg or "fixes" in commit_msg:
    issue_checker=True
if "Feature" in commit_msg or "feature" in commit_msg:
    feature_checker=True
if issue_checker & feature_checker:
    print("Issue and feature information submitted correctly!")
else:
    print("Checking for merge message...")
    if "Merge branch" in commit_msg:
        print("Merge message accepted!")
    else:
        print("Incorrect format")
        print("Please Use The Correct Commit Message Format")
        print("E.g. git commit -m 'Example commit message [Feature X] [Fixes #21]'")
        sys.exit(1)   

