#!/usr/bin/env python
import sys, re, os
from subprocess import check_output
analyze_result=os.system("flutter analyze")
test_result=os.system("flutter test")
if analyze_result==0 and test_result==0:
    print("Analysis and Tests Passed")
else:
    print("Tests Failed, Please review your code!")
    sys.exit(1)